name: Continuity

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [main]
    paths-ignore:
      - 'reflections/**'
      - 'AI_Responses/**'

jobs:
  reflect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install openai gitpython

      - id: date
        run: echo "utc=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> "$GITHUB_OUTPUT"

      - name: Run reflection
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python .github/scripts/ai_reflect.py ${{ github.event_name }} ${{ github.event.after || github.sha }}

      - name: Run self-assembly if present
        run: |
          if [ -f scripts/self_assembly/auto_self_assemble.py ]; then
            python scripts/self_assembly/auto_self_assemble.py
          fi

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "VybnAI"
          git config user.email "actions@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "Vybn continuity update ${{ steps.date.outputs.utc }}"
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
            git push origin HEAD:main
          else
            echo "No changes to commit."
          fi

